//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GradePredictor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GradePredictor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.0.
        /// </summary>
        internal static string ASSESSMENT_DEFAULT_RESULT {
            get {
                return ResourceManager.GetString("ASSESSMENT_DEFAULT_RESULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assessment.
        /// </summary>
        internal static string ASSESSMENT_DEFAULT_TITLE {
            get {
                return ResourceManager.GetString("ASSESSMENT_DEFAULT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string ASSESSMENT_DEFAULT_TYPE {
            get {
                return ResourceManager.GetString("ASSESSMENT_DEFAULT_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string ASSESSMENT_DEFAULT_WEIGHT {
            get {
                return ResourceManager.GetString("ASSESSMENT_DEFAULT_WEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 55.
        /// </summary>
        internal static string ASSESSMENT_POSITION_MULTIPLIER {
            get {
                return ResourceManager.GetString("ASSESSMENT_POSITION_MULTIPLIER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Course.
        /// </summary>
        internal static string COURSE_DEFAULT_TITLE {
            get {
                return ResourceManager.GetString("COURSE_DEFAULT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30000.
        /// </summary>
        internal static string COURSE_SAVE_INTERVAL {
            get {
                return ResourceManager.GetString("COURSE_SAVE_INTERVAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IconDeleteLarge {
            get {
                object obj = ResourceManager.GetObject("IconDeleteLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IconDeleteMedium {
            get {
                object obj = ResourceManager.GetObject("IconDeleteMedium", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IconLoadMedium {
            get {
                object obj = ResourceManager.GetObject("IconLoadMedium", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IconPencilMedium {
            get {
                object obj = ResourceManager.GetObject("IconPencilMedium", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IconPencilSmall {
            get {
                object obj = ResourceManager.GetObject("IconPencilSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IconPlusMedium {
            get {
                object obj = ResourceManager.GetObject("IconPlusMedium", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IconRestartMedium {
            get {
                object obj = ResourceManager.GetObject("IconRestartMedium", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IconSaveMedium {
            get {
                object obj = ResourceManager.GetObject("IconSaveMedium", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CODE-000.
        /// </summary>
        internal static string MODULE_DEFAULT_CODE {
            get {
                return ResourceManager.GetString("MODULE_DEFAULT_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string MODULE_DEFAULT_CREDITS {
            get {
                return ResourceManager.GetString("MODULE_DEFAULT_CREDITS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module Title.
        /// </summary>
        internal static string MODULE_DEFAULT_TITLE {
            get {
                return ResourceManager.GetString("MODULE_DEFAULT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 55.
        /// </summary>
        internal static string MODULE_POSITION_MULTIPLIER {
            get {
                return ResourceManager.GetString("MODULE_POSITION_MULTIPLIER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string MODULE_POSITION_OFFSET {
            get {
                return ResourceManager.GetString("MODULE_POSITION_OFFSET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15.
        /// </summary>
        internal static string MODULE_STANDARD_CREDIT_VALUE {
            get {
                return ResourceManager.GetString("MODULE_STANDARD_CREDIT_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to course-autosave.course.
        /// </summary>
        internal static string SAVE_FILE_PATH {
            get {
                return ResourceManager.GetString("SAVE_FILE_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The assessments result is invalid. It will be ignored in the calculation..
        /// </summary>
        internal static string WARNING_MESSAGE_ASSESSMENT_INVALIDRESULT {
            get {
                return ResourceManager.GetString("WARNING_MESSAGE_ASSESSMENT_INVALIDRESULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The assessments weight is set to 0. It will be ignored in the calculation..
        /// </summary>
        internal static string WARNING_MESSAGE_ASSESSMENT_NOWEIGHT {
            get {
                return ResourceManager.GetString("WARNING_MESSAGE_ASSESSMENT_NOWEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The course has insufficient data to perform the calculation..
        /// </summary>
        internal static string WARNING_MESSAGE_COURSE_INSUFFDATA {
            get {
                return ResourceManager.GetString("WARNING_MESSAGE_COURSE_INSUFFDATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The course has interpolated some values that were missing. The result is a very rough prediction..
        /// </summary>
        internal static string WARNING_MESSAGE_COURSE_INTERPOLATED {
            get {
                return ResourceManager.GetString("WARNING_MESSAGE_COURSE_INTERPOLATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A module you have entered has a REF result. Current application settings recognize this as a degree failure condition..
        /// </summary>
        internal static string WARNING_MESSAGE_COURSE_REFFAIL {
            get {
                return ResourceManager.GetString("WARNING_MESSAGE_COURSE_REFFAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The final degree result could not be calculated..
        /// </summary>
        internal static string WARNING_MESSAGE_COURSE_RESULTNA {
            get {
                return ResourceManager.GetString("WARNING_MESSAGE_COURSE_RESULTNA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A module you have entered has a FAIL result. Current application settings recognize this as a degree failure condition..
        /// </summary>
        internal static string WARNING_MESSAGE_COURSE_RETAKEFAIL {
            get {
                return ResourceManager.GetString("WARNING_MESSAGE_COURSE_RETAKEFAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A level 6 module has a FAIL result. This is recognized as a degree failure condition..
        /// </summary>
        internal static string WARNING_MESSAGE_COURSE_RETAKESIXFAIL {
            get {
                return ResourceManager.GetString("WARNING_MESSAGE_COURSE_RETAKESIXFAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The assessments in this module have inconsistent total weight. The weights will be rescaled..
        /// </summary>
        internal static string WARNING_MESSAGE_MODULE_INCONSASSESSMENTS {
            get {
                return ResourceManager.GetString("WARNING_MESSAGE_MODULE_INCONSASSESSMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The module has an invalid credit value. It will be ignored in the calculation..
        /// </summary>
        internal static string WARNING_MESSAGE_MODULE_INVALIDCREDITS {
            get {
                return ResourceManager.GetString("WARNING_MESSAGE_MODULE_INVALIDCREDITS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The module has an invalid result. It will be ignored in the calculation..
        /// </summary>
        internal static string WARNING_MESSAGE_MODULE_INVALIDRESULT {
            get {
                return ResourceManager.GetString("WARNING_MESSAGE_MODULE_INVALIDRESULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The module contains no usable assessments. It will be ignored in the calculation..
        /// </summary>
        internal static string WARNING_MESSAGE_MODULE_NOASSESSMENTS {
            get {
                return ResourceManager.GetString("WARNING_MESSAGE_MODULE_NOASSESSMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The module does not have a credit value. It will be ignored in the calculation..
        /// </summary>
        internal static string WARNING_MESSAGE_MODULE_NOCREDITS {
            get {
                return ResourceManager.GetString("WARNING_MESSAGE_MODULE_NOCREDITS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The module has a non-standard credit value, this may or may not be an error..
        /// </summary>
        internal static string WARNING_MESSAGE_MODULE_NONSTANDCREDITS {
            get {
                return ResourceManager.GetString("WARNING_MESSAGE_MODULE_NONSTANDCREDITS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The year has non-standard credit total. The modules will be rescaled to try and match standard values..
        /// </summary>
        internal static string WARNING_MESSAGE_YEAR_INCONSCREDITS {
            get {
                return ResourceManager.GetString("WARNING_MESSAGE_YEAR_INCONSCREDITS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The year contains no usable modules. It will be ignored in the calculation..
        /// </summary>
        internal static string WARNING_MESSAGE_YEAR_NOMODULES {
            get {
                return ResourceManager.GetString("WARNING_MESSAGE_YEAR_NOMODULES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The result for this year could not be calculated..
        /// </summary>
        internal static string WARNING_MESSAGE_YEAR_NORESULT {
            get {
                return ResourceManager.GetString("WARNING_MESSAGE_YEAR_NORESULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to false.
        /// </summary>
        internal static string X_FAIL_ON_REF {
            get {
                return ResourceManager.GetString("X_FAIL_ON_REF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to false.
        /// </summary>
        internal static string X_FAIL_ON_RETAKE {
            get {
                return ResourceManager.GetString("X_FAIL_ON_RETAKE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to false.
        /// </summary>
        internal static string X_STOP_ON_MISSING {
            get {
                return ResourceManager.GetString("X_STOP_ON_MISSING", resourceCulture);
            }
        }
    }
}
